version: '3.8'

services:
  backend:
    build: ./backend
    container_name: myapp-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: myapp-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: myapp-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
